#!/bin/bash
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 [user@]hostname";
    exit 1;
fi

ssh $1 'command -v fish >/dev/null 2>&1 || { echo >&2 "fish absent"; exit 1; }; grep `which fish` /etc/shells || { echo >&2 "fish not in shells"; exit 1; }; chsh -s `which fish`'
rsync -Lrz ~/.vimrc ~/.vim ~/.gitconfig $1:

