#!/usr/bin/env perl
use strict;
use warnings;

die "usage: $0 [user@]hostname" unless @ARGV == 1;
my $host = shift;
my @ssh_command;
my @rsync_command;

if ($host eq '.') { # vagrant
    die "Not in a Vagrant directory" unless -e "Vagrantfile";

    @ssh_command = ('vagrant', 'ssh', '-c');

    my $ssh_config = `vagrant ssh-config`;
    my $ssh_args = join " ", map { s/^  (\w+)\s+(.+)$/-o $1=$2/r } grep { /^\s+\S/ } split /\n/, $ssh_config;

    @rsync_command = ("rsync", "-e", "ssh $ssh_args");
}
else {
    @ssh_command = ('ssh', $host);
    @rsync_command = ('rsync');
}

system(@ssh_command, q[bash -c '
if [ -e ~/.bin ]; then
    (cd ~/.bin; git pull --quiet)
else
    git clone https://github.com/sartak/bindir.git ~/.bin;
fi;

command -v fish >/dev/null 2>&1 || { echo >&2 "fish absent"; exit 1; };
grep -q `which fish` /etc/shells || { echo >&2 `which fish` "not in shells"; exit 1; };
if [ `getent passwd $LOGNAME | cut -d: -f7` != `which fish` ]; then
    chsh -s `which fish`;
fi;
']);

chdir $ENV{HOME};
system(@rsync_command,
    "-LRrz",
    ".vimrc",
    ".vim",
    ".gitconfig",
    ".config/fish/config.fish",
    "$host:",
);
