require("config.sartak.disable")
require("config.sartak.mappings")
require("config.sartak.indent")
require("config.sartak.autosave")
require("config.sartak.completion")
require("config.sartak.fzf")
require("config.sartak.undo")
