require("config.sartak.autosave")
require("config.sartak.completion")
require("config.sartak.diagnostics")
require("config.sartak.fzf")
require("config.sartak.lsp")
require("config.sartak.mappings")
require("config.sartak.mouse")
require("config.sartak.sql")
